module.exports = {
  Core: require('./structures/Core'),
  Collection: require('./util/Collection'),
  Command: require('./structures/Command'),
  Event: require('./structures/Event'),
  UniqueId: require('./util/UniqueId'),
  Mongo: require('./structures/Mongo'),
  Embed: require('./structures/Embed'),
  PermissionLevels: require('./structures/PermissionLevels'),
  Pages: require('./structures/Pages'),
  MySql: require('./structures/MySql'),
  Store: require('./structures/Store'),
  Monitor: require('./structures/Monitor'),
  Trigger: require('./structures/Trigger'),
  Inhibitor: require('./structures/Inhibitor'),
};
